### ISSUE TITLE
merging dataset only supports ".png", ".jpg" format?

### ISSUE THREAD

**Issue by cvchongci** [ashnair1/COCO-Assistant#20]
Thanks for the great tool. I have two questions about multiple dataset merging:
1. does merging dataset function only support ".png", ".jpg" format? I found the following codes
```
if merge_images:
            print("Merging image dirs")
            im_dirs = [os.path.join(self.img_dir, folder) for folder in self.imgfolders]
            imext = [".png", ".jpg"]
```
2. 
```
for imdir in tqdm(im_dirs):
                ims = [i for i in os.listdir(imdir) if i[-4:].lower() in imext]
                for im in ims:
                    shutil.copyfile(os.path.join(imdir, im), os.path.join(self.resim_dir, im))
```
different datasets to be merged should not contain images which have the same name? for example, I have 2 datasets: A_dataset, B_dataset. in A_dataset I have an image named 1.jpg. and in B_dataset I also have an image named 1.jpg. then what will happen for this case?

thank you so much.

**Comment by ashnair1** [comment]
1. The choice of `.png` and .`jpg` were simply because most datasets use these formats. Additionally, the original MS-COCO dataset had images in `.jpg` format. 
2. Presently, it's expected that names should not overlap. So if you have `1.jpg` in datasets A and B, merging images will cause the `1.jpg` of A to be overwritten by `1.jpg` of B. The produced annotation would be invalid as well.

**Comment by cvchongci** [comment]
Thanks for the clarification.
