### ISSUE TITLE
Add feature to merge negative images (images with no segmentation) json files

### ISSUE THREAD

**Issue by reubenwenisch** [ashnair1/COCO-Assistant#52]
Training certain networks using transfer learning for segmentation leads to lots of false positives. One method is to feed negative or background images to the network. 
The ability for coco assistant to help merge negative samples would be a good feature to my understanding.

**Comment by ashnair1** [comment]
I'm going to assume we're talking about instance segmentation (objects with masks) rather than semantic segmentation (pixelwise masks).

AFAIK there is no official specification for negative samples i.e. images without annotation for MS COCO. From what I've read, if you're using neural network based object detection there is no need for negative images as negative regions are already considered. Areas where your object is absent is implicitly a negative region. So if you're building a cat detector, image regions which do not have a cat are the negative regions.

**Comment by ashnair1** [comment]
A negative sample is essentially an image without annotation. So if you really want to include such images, you could just add image metadata to the image field in the json file. The merge operation in COCO Assistant merges the fields (images, annotation etc) separately so theoretically you could merge such datasets. However then you will need to account for this when you load your data and while building your model.
